### ISSUE TITLE
Create an API

### ISSUE THREAD

**Issue by shayan786** [simonkrauter/Open-EV-Charts#1]
Hey,

Not exactly an issue but i can create you an api on my open-source project, prob way more efficient than `.js` files ... lmk if you're interested ....

https://gettingev.com

API docs: https://gettingev.com/api/documentation/v1.0.0

**Comment by simonkrauter** [comment]
Hey,

the idea of Open EV Charts was and is, that it runs completely in the browser, so anyone can easily clone it, change some files and see the effect. An API needs a server, a database and an admin frontend to enter the data.
Let me ask you, what exactly is your proposal and the benefit? What I could think of, is to have an API in addition to the JS files.
 
btw, what do you think of adding a link to https://open-ev-charts.org/ on https://gettingev.com/resources ? :)

**Comment by shayan786** [comment]
I'm approaching it from a CMS perspective for non-technical users ... so all of the api work on my end is already automated by open source tools and would provide a really streamlined way directly from the browser rather than clone or fork a codebase but just my opinion ... i understand why you did it the way you did though so its all good.

Added to resources ... 👍

**Comment by shayan786** [comment]
fyi, i've started entering the data at this endpoint in case anyone wants to use the public api.

https://gettingev.com/api/sales
