### ISSUE TITLE
Access to our db

### ISSUE THREAD

**Issue by maximeLpt** [simonkrauter/Open-EV-Charts#2]
Hi,

I wanted to know if it is possible to request your database directly from my python script?

Thanks

**Comment by simonkrauter** [comment]
Hi,

no, at least not over open-ev-charts.org, it serves only JavaScript files which are executed in the browser.
You could read the raw data by downloading and parsing the 'data' files, they are simple JavaScript files.
About providing an API: see #1, maybe ask user shayan786 if he can help you.

btw, what is you idea to create?
