### ISSUE TITLE
Feature request: group by company vs brands

### ISSUE THREAD

**Issue by thburghout** [simonkrauter/Open-EV-Charts#3]
For a more real realistic view of company market percentage it is favorable to look at the owning companies of the brands versus the individual brands.

![image](https://user-images.githubusercontent.com/25661722/125159174-1a62b880-e176-11eb-9222-7c432c6da952.png)

**Comment by simonkrauter** [comment]
Good idea. I could think of implementing a grouping of brands like in the picture.

**Comment by simonkrauter** [comment]
Implemented by https://github.com/simonkrauter/Open-EV-Charts/commit/837e45b921afc92e1667344dae92c364535d44ac.
The feature is not yet complete (filter missing).
Feedback welcome.
