### ISSUE TITLE
Data for Iceland

### ISSUE THREAD

**Issue by birkir** [simonkrauter/Open-EV-Charts#4]
https://bifreidatolur.samgongustofa.is/#tolfraedi

It's a PowerBI dashboard, let me know if u need help.

**Comment by simonkrauter** [comment]
Hi, looks interesting. Unfortunately I don't see any export or copy to clipboard function. Do you have any idea how to extract the data?

**Comment by simonkrauter** [comment]
The data for Iceland is now added.
Looking for data sources for more countries to add.
