### ISSUE TITLE
Wrong data: EV market share China in March 2024

### ISSUE THREAD

**Issue by TimmFromHamburg** [simonkrauter/Open-EV-Charts#8]
Hey,

It looks like the data for the market share of EVs in China in March 2024 is not correct in the database. The linked source for China (https://cleantechnica.com/2024/04/27/43-plugin-vehicle-market-share-in-china-march-2024-sales-report/)

shows 28% share instead of the 16% shown in the Open-EV-Database.

Thanks.

And btw.: awesome work! the data base is gerat! Thanhs for alle the efford!

Best,
Timm

**Comment by simonkrauter** [comment]
Hi,

thanks a lot for your attention!
The mistake is now fixed by https://github.com/simonkrauter/Open-EV-Charts/commit/67e212b06417cb8a0542269a9be96dc8d570c323.
